# Generated by Django 6.0.3 on 2026-04-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документов',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=64, unique=True, verbose_name='код сотрудника')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('profession_key', models.CharField(db_index=True, max_length=64, verbose_name='ключ профессии')),
                ('profession_label', models.CharField(blank=True, max_length=255, verbose_name='профессия (подпись)')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('submitted', 'отправлена'), ('ready', 'готова'), ('sent', 'отправлено'), ('cancelled', 'отменена')], default='draft', max_length=16, verbose_name='статус')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='параметры пакета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to='pass_docs.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'заявка на пакет',
                'verbose_name_plural': 'заявки на пакеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('missing', 'нет в комплекте'), ('pending', 'на проверке'), ('ok', 'принят'), ('expired', 'просрочен'), ('rejected', 'отклонён')], default='pending', max_length=16, verbose_name='статус')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='внешний номер / реквизиты')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действителен до')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='метаданные импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='pass_docs.documenttype', verbose_name='тип документа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pass_docs.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'документ сотрудника',
                'verbose_name_plural': 'документы сотрудников',
                'ordering': ['employee', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'document_type'), name='pass_docs_unique_employee_document_type')],
            },
        ),
        migrations.CreateModel(
            name='ProfessionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_key', models.CharField(db_index=True, max_length=64, verbose_name='ключ профессии')),
                ('profession_label', models.CharField(blank=True, max_length=255, verbose_name='подпись профессии')),
                ('is_required', models.BooleanField(default=True, verbose_name='обязателен')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_requirements', to='pass_docs.documenttype', verbose_name='тип документа')),
            ],
            options={
                'verbose_name': 'требование к профессии',
                'verbose_name_plural': 'требования к профессиям',
                'ordering': ['profession_key', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('profession_key', 'document_type'), name='pass_docs_unique_profession_document_type')],
            },
        ),
    ]
