# Generated by Django 6.0.3 on 2026-04-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('extractor_kind', models.CharField(blank=True, default='', help_text='Идентификатор пайплайна извлечения (позже vision и т.д.).', max_length=64, verbose_name='тип экстрактора')),
                ('is_common_document', models.BooleanField(default=False, verbose_name='общий документ')),
                ('expiry_rule_days', models.PositiveIntegerField(blank=True, help_text='Опциональное правило: через сколько дней истекает документ.', null=True, verbose_name='срок действия, дней')),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документов',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=64, unique=True, verbose_name='код сотрудника')),
                ('full_name', models.CharField(max_length=512, verbose_name='ФИО (как в источнике)')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='фамилия')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='отчество')),
                ('profession_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ключ профессии')),
                ('profession_label', models.CharField(blank=True, max_length=255, verbose_name='профессия (подпись)')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='организация')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('iin', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='ИИН/идентификатор')),
                ('passport_series', models.CharField(blank=True, max_length=16, verbose_name='серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=32, verbose_name='номер паспорта')),
                ('passport_full_number', models.CharField(blank=True, max_length=64, verbose_name='паспорт полностью')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['full_name', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_kind', models.CharField(blank=True, max_length=64, verbose_name='вид пакета')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('submitted', 'отправлена'), ('ready', 'готова'), ('sent', 'отправлено'), ('cancelled', 'отменена')], default='draft', max_length=16, verbose_name='статус')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='данные заявки')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='pass_docs/packages/%Y/%m/', verbose_name='Excel')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='pass_docs/packages/%Y/%m/', verbose_name='ZIP')),
                ('email_to', models.CharField(blank=True, max_length=512, verbose_name='email получателя')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_requests', to='pass_docs.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'заявка на пакет',
                'verbose_name_plural': 'заявки на пакеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='pass_docs/uploads/%Y/%m/', verbose_name='файл')),
                ('source_path', models.TextField(verbose_name='путь к исходному файлу')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='срок действия')),
                ('extracted_json', models.JSONField(blank=True, default=dict, verbose_name='результат извлечения')),
                ('parse_status', models.CharField(choices=[('pending', 'ожидает разбора'), ('skipped', 'пропущен'), ('ok', 'разобран'), ('error', 'ошибка')], default='pending', max_length=16, verbose_name='статус разбора')),
                ('status', models.CharField(choices=[('missing', 'нет в комплекте'), ('pending', 'на проверке'), ('ok', 'принят'), ('expired', 'просрочен'), ('rejected', 'отклонён')], default='pending', max_length=16, verbose_name='статус комплекта')),
                ('is_actual', models.BooleanField(default=True, verbose_name='актуален')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='внешний номер / реквизиты')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='метаданные импорта')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='pass_docs.documenttype', verbose_name='тип документа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pass_docs.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'документ сотрудника',
                'verbose_name_plural': 'документы сотрудников',
                'ordering': ['employee', 'document_type', 'source_path'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'source_path'), name='pass_docs_unique_employee_source_path')],
            },
        ),
        migrations.CreateModel(
            name='ProfessionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_key', models.CharField(db_index=True, max_length=64, verbose_name='ключ профессии')),
                ('profession_label', models.CharField(blank=True, max_length=255, verbose_name='подпись профессии')),
                ('required_for_initial', models.BooleanField(default=True, verbose_name='нужен при первичном оформлении')),
                ('required_for_renewal', models.BooleanField(default=True, verbose_name='нужен при продлении')),
                ('required_for_transport', models.BooleanField(default=False, verbose_name='нужен для транспорта')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_requirements', to='pass_docs.documenttype', verbose_name='тип документа')),
            ],
            options={
                'verbose_name': 'требование к профессии',
                'verbose_name_plural': 'требования к профессиям',
                'ordering': ['profession_key', 'document_type'],
                'constraints': [models.UniqueConstraint(fields=('profession_key', 'document_type'), name='pass_docs_unique_profession_document_type')],
            },
        ),
    ]
