# Generated by Django 6.0.3 on 2026-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_docs', '0002_folder_identity_employee_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'черновик'), ('submitted', 'отправлена'), ('building', 'сборка'), ('ready', 'готова'), ('failed', 'ошибка сборки'), ('sent', 'отправлено'), ('cancelled', 'отменена')], default='draft', max_length=16, verbose_name='статус'),
        ),
    ]
